### ISSUE TITLE
DB Schema

### ISSUE THREAD

**Issue by BCrawfordScott** [ycherradi/remorph-project#2]
Great work, a few changes for approval:

- [x] Remove categoryId from campaigns - campaigns can likely belong to more than one category, yes? In that case, we'll want a joins table so that campaigns can have many categories and categories can have many campaigns.  (Disregard if campaigns can only ever have one catergory)
- [x] I'd suggest leaving the `bank_accounts` table as a bonus. We won't actually collect any financial information in this project, so there's no need for it now.

**Comment by ycherradi** [comment]
Hi Brian,

I want to have each campaign belong to only one category. 
Is what I have good for that or do I still need to implement a joins table?

Thank You
Yassine Cherradi

**Comment by BCrawfordScott** [comment]
If it's 1:1, no need for the joins :+1:

**Comment by ycherradi** [comment]
Thank you
